app:
  title: 이미지 Resize API
  summary: 이미지의 특정 이미지를 제외하고 재생성하기 위한 백엔드
  version: 0.1.0
  description: |
    특정 이미지를 제거하고 재생성하는 역할을 함

    ## Mechanism
    1. 제외해야 할 이미지들을 미리 파일로 저장되어있다.
    2. 요청이 이미지와 함께 들어온다.
    3. 이미지에 제외할 이미지가 있는지 체크한다.
    4. 없으면 그냥 되돌린다.
    5. 있음 편집하고 편집한 이미지를 되돌려준다.